FROM bandi13/gui-docker

USER root

RUN eval ${APT_INSTALL_PRE} firefox ${APT_INSTALL_POST}
RUN echo "?package(bash):needs=\"X11\" section=\"DockerCustom\" title=\"Firefox\" command=\"firefox\"" >> /usr/share/menu/custom-docker && update-menus

USER dockerUser
